### PR TITLE
Simplify NewConfig description

### PR DESCRIPTION
**Pull request by grtcdr**
The current description is in my opinion longer than it should be. I propose compiling the accepted values into a list rather than describing them through words.

### CODE REVIEW

**Comment by grtcdr** [comment]
I also noticed that some words were abbreviated, while others were not. In this case I'll refer you to two separate descriptions which both say the same thing about supporting ENV variables, but they say it differently. I suggest keeping the descriptions with one another.

See:

https://github.com/SchoofsKelvin/vscode-sshfs/blob/48ef2298a8985c5748680d66477ea31c841f8592/webview/src/ConfigEditor/fields.tsx#L102

And:

https://github.com/SchoofsKelvin/vscode-sshfs/blob/48ef2298a8985c5748680d66477ea31c841f8592/webview/src/ConfigEditor/fields.tsx#L94

**Comment by grtcdr** [comment]
@SchoofsKelvin Would you like me to work on the other descriptions?

**Comment by SchoofsKelvin** [comment]
I'll go through the descriptions. It's true that most of them are more written from a technical standpoint than a consistent UI-wise one. _You might've noticed that those descriptions are basically identical to the JSDocs for the targeted fields._

**Comment by grtcdr** [comment]
> You might've noticed that those descriptions are basically identical to the JSDocs for the targeted fields.

I haven't, actually. I've never used or read through JSDoc's docs before.

> You can do that if you want and create a new PR. 

Great, I'll get to it :)

**Comment by SchoofsKelvin** [comment]
> I've never used or read through JSDoc's docs before.

I meant the JSDoc comments on [this file](https://github.com/SchoofsKelvin/vscode-sshfs/blob/master/src/fileSystemConfig.ts) and [this file](https://github.com/SchoofsKelvin/vscode-sshfs/blob/master/webview/src/types/fileSystemConfig.ts). _They're actually the same file present in both projects (the extension itself and the frontend used for the Settings UI), seemed a bit over the top to create a whole common/shared module for just that bit of code._ The settings fields are almost perfectly 1-on-1 mapped upon the fields of that config. I mostly copied the descriptions from the `FileSystemConfig` fields straight to the Settings UI fields.

**Comment by grtcdr** [comment]
Oh, okay, I get it now.

> seemed a bit over the top to create a whole common/shared module for just that bit of code. 

But that would just make it a maintenance burden for you if you were to make any modification, right?

**Comment by SchoofsKelvin** [comment]
> But that would just make it a maintenance burden for you if you were to make any modification, right?

Right now, whenever I modify something in one of the files, I _should_ update the other file too. Small burden, and in the end still less work than setting up a whole new module, setting up imports/exports/dependencies, plugging it into the build pipelines, ... which would also increase the build complexity/duration.

And besides, even if both files deviate, not a big issue. As long as each file contains the things that are needed in its project and don't have conflicts, it's not even an issue if I forget.

If I at some point end up with a lot more shared code _(which might happen once I add proper Settings UI support for something complex like [feature/forwarding](https://github.com/SchoofsKelvin/vscode-sshfs/tree/feature/forwarding))_, I can still decide to create a common module.

**Comment by grtcdr** [comment]
Oh okay, thanks for the thorough explanation :)

**Pull request merged**
